receivers:
  otlp:
    protocols:
      grpc:
      http:
  # Prometheus receiver removed as it's not used and 'endpoint' is an invalid key for it.

processors:
  batch:
  resourcedetection:
    detectors: [env, system]
    timeout: 2s
    system:
      hostname_sources: [os]

exporters:
  prometheus:
    endpoint: "0.0.0.0:9091" # Prometheus exporter will expose metrics on this port
  loki:
    endpoint: "http://loki-server:3100/loki/api/v1/push"
  otlp/tempo:
    endpoint: "tempo-server:4317"
    tls:
      insecure: true
  clickhousetraces:
    datasource: tcp://signoz-clickhouse:9000
    docker_multi_node_cluster: false
  clickhousemetricswrite:
    endpoint: tcp://signoz-clickhouse:9000
    resource_to_telemetry_conversion:
      enabled: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/tempo, clickhousetraces]
    metrics:
      receivers: [otlp]
      processors: [batch, resourcedetection]
      exporters: [prometheus, clickhousemetricswrite]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [loki]
  telemetry:
    metrics:
      address: 0.0.0.0:8888 # Internal telemetry metrics will be exposed on this port
